### ISSUE TITLE
Centos 6

### ISSUE THREAD

**Issue by yiyunalu** [lamyj/dicomifier#39]
It look likes it required glibc-2.14 for dependecy.
Is it compatible with Centos 6 since centos 6 only have 2.12 version as the newest.

**Comment by lamyj** [comment]
Even if the glibc version was OK (which I guess could be, since we're only facing a slight jump in minor versions), the version of Python bundled with CentOS 6 is too old (2.6.6 vs. 2.7 as required by dicomifier) and there would also be the C++ problems when compiling [Odil](https://github.com/lamyj/odil), on which Dicomifier depends (cf. my comment in lamyj/packages#1).
